### ISSUE TITLE
Exclusion Folders Resets after Manual Sort

### ISSUE THREAD

**Issue by megamorphg** [eric-bixby/auto-sort-bookmarks-webext#112] opened 2022-08-31 04:29 UTC
After setting up exclusions and then running the sort manually, it works and excludes properly.
However, the exclusions got reset.

Steps to reproduce:
1. Setup exclusions. Note the Recursive exclusions:
![image](https://user-images.githubusercontent.com/1782353/187592808-99e51bfd-39b1-4b44-8b79-8c4fd011f8ea.png)
2. Run the Sort action from Add-On actions.
3. Wait for action to complete.
4. Observe that the Exclusions are reset:
![image](https://user-images.githubusercontent.com/1782353/187592946-5bec668c-fef8-4195-9990-665ce7fa09b1.png)

**Comment by eric-bixby** [comment] 2022-10-30 00:43
Duplicate of #75

**Closed by eric-bixby** 2022-10-30 00:43 UTC
