### ISSUE TITLE
Option to ignore Bookmark Toolbar (or exclude any folder)

### ISSUE THREAD

**Issue by shangles** [eric-bixby/auto-sort-bookmarks-webext#54] opened 2017-11-26 22:00 UTC
There was an option in the pre-v57 Firefox add-on to ignore the Bookmark Toolbar, which I always had enabled.  I just installed your latest for v57 (THANK YOU!) but noticed in the options that there wasn't a setting for this.  Is that coming in a future release?

**Comment by eric-bixby** [comment] 2017-11-26 22:10
Yes, that's the plan.

**Comment by shangles** [comment] 2017-11-26 22:10
Thank you for the speedy response.  Again, great work on getting this handy add-on working in v57!

**Comment by Taurean75** [comment] 2017-11-26 23:42
I badly need this also.

**Comment by molitar** [comment] 2017-12-05 04:00
Yeah now my bookmarks are all screwed up!  I had to disable this addon since last update broke ignore bookmarks!

**Comment by AntonioRedondo** [comment] 2017-12-05 07:46
I agree with @molitar it would have being nice if the new version was launched WITH this feature already implemented. This had the consequence that now the bookmarks of the bookmarks toolbar are messed up.

**Comment by Taurean75** [comment] 2017-12-05 20:32
@AntonioRedondo & @molitar, I believe you can restore your bookmarks within the bookmark library.

**Comment by molitar** [comment] 2017-12-06 03:36
I was lucky my weekly backup just happened the night before so I just overwrote my browser local and roaming folder and than started in safe mode and disabled this app.

**Comment by Taurean75** [comment] 2017-12-06 03:38
@molitar, you'd enable sync.

**Comment by eric-bixby** [comment] 2017-12-06 04:47
**Status Update**
For those anxiously waiting for the exclude folders feature, I want to let you know the situation.

First, some background. The way this feature worked in ASB 2.X was to add a tag (also called annotation) of "excluded" and/or "resurivelyExcluded" to the folder. The advantage to this approach is that the tags are part of your bookmarks so it can be synced with other computers.

The bad news is that WebExtensions does not and will likely never support tags/annotations. Chrome doesn't have descriptions and it doesn't have tags/annotations. Have bookmarks descriptions is why I liked Firefox over Chrome.

<rant> It pisses me off that Mozilla decided to implement WebExtensions. You can't drop a Firefox add-on (using WebExtension) into Chrome and vice versa.  They are similar but different.  This is complete and utter marketing bullshit. </rant>

Here's a Firefox bug for this issue (it's long and disappointing to read):
https://bugzilla.mozilla.org/show_bug.cgi?id=1225916

The good news is that I'm trying to workaround this limitation.  I'm planning to store the excluded folder settings with the other settings.  However, there are a couple of obstacles I need to work out:
1) Settings/preferences do not currently sync between computers (assuming you have more than one).
2) Need to decide what to use as the key for each exclusion.  I could use the folder 'id', which is fine for the root folders (menu-folder, toolbar-folder, other-folder) because they have set ids.  However, ids for folders may vary between computers, even if you use a bookmark sync tool.  I could use the folder title instead, but this may not be unique (you can have different sub-folders with the same title).

**Comment by shangles** [comment] 2017-12-06 16:06
Thank you for the update!

**Comment by Taurean75** [comment] 2017-12-06 17:41
> I could use the folder title instead, but this may not be unique...

@eric-bixby, I'd suggest using full path names for this; e.g., "Bookmark Toolbar\Live". This way, it'd be unique enough.

**Comment by eric-bixby** [comment] 2017-12-06 17:57
Yes, I thought of this too. The disadvantage to this is that if a folder is moved or renamed, then the user must update the exclusion. I could have the addon listen for the folder move/rename event to automatically update the exclusion, but this only works if the addon is running when the change happens. Otherwise it’s a manual change. Whereas this isn’t a problem if the ID is used.

**Comment by Taurean75** [comment] 2017-12-06 18:02
@eric-bixby, just forget about the sync for now and use the IDs.

**Comment by eric-bixby** [comment] 2017-12-08 07:15
I thought of another option.  Add a prefix or postfix to the folder title.  That way it would be synced with the folders.  The root folders would just be by id and they could be selected by check-boxes.  The user folder would have the prefix or postfix.  Like "NS-My Folder" (no sort) and "RNS-My Folder" (recursively no sort) or "My Folder-NS" and "My Folder-RNS".  Also, let the user decide what the prefix or postfix text is.

Thoughts?

**Comment by eric-bixby** [comment] 2017-12-08 18:30
I can't.  Tags and Description are not supported by WebExtensions.

**Comment by eric-bixby** [comment] 2017-12-08 18:31
I'm going to provide the option of using the folder id and/or folder title to exclude folders.

**Comment by shangles** [comment] 2017-12-09 03:47
Pardon my ignorance, but do your suggestions involve me (us) modifying every one of our bookmark folders to add a prefix somewhere?

**Comment by Taurean75** [comment] 2017-12-09 03:50
@shangles, just the folders.

**Comment by shangles** [comment] 2017-12-09 04:01
Yes, that's what I asked.  So if, in my bookmark library, I have 50+ folders to organize bookmarks, I'll need to update each of those?

**Comment by eric-bixby** [comment] 2017-12-09 04:37
Either the add-on could add/remove the folder or the user could do it manually. 
However, if the 50+ folders are under the same parent folder, like say Toolbar, then you would just recursively exclude the Toolbar folders (single action) and the child folders would also be excluded. Whereas, if the folders under the parent folder are mixed (some excluded and others not) then you have to individually mark the ones to exclude.

**Comment by shangles** [comment] 2017-12-09 05:02
Ahh OK.  That makes sense.  So in my case it would just be on the Bookmark Toolbar folder that I'd want to exclude.  Thanks for the explanation.

**Comment by molitar** [comment] 2017-12-09 07:49
yeah Bookmark Toolbar is all I want to exclude also. I like everything else sorted but the toolbar I have the icons in order I use them in most often.

**Comment by eric-bixby** [comment] 2017-12-25 17:25
Here's a beta release to try:
https://github.com/eric-bixby/auto-sort-bookmarks-webext/releases/tag/v3.2beta1

1) Backup your bookmarks.
2) Install add-on by entering "about:debugging" into addressbar.
3) Select "Load Temp Add-on"
4) Select the .xpi file downloaded using the URL given above.

**Comment by Taurean75** [comment] 2017-12-25 20:07
It works great and seems faster!

**Comment by shangles** [comment] 2017-12-28 19:46
I installed the latest beta and unchecked Bookmark Toolbar in the Configure Folders section and saved my changes.  I also checked the Auto-Sort box (and saved changes)

I added a new bookmark but it's not auto-sorting.  If I look at the Options for Configure Folders, the "recursive" box next to Bookmarks Menu is unchecked and grayed out so I can't check it.  I'm assuming that's why it's not sorting the new bookmark automatically in one of the subfolders?

**Comment by shangles** [comment] 2017-12-28 19:50
Ignore that.  I went back and fumbled with some of the checkboxes and repeated my steps, and the new bookmark is now sorting as expected.

**Comment by eric-bixby** [comment] 2017-12-28 23:38
Glad you figured it out.  FYI for everyone else.

The "Configure Folders" feature works exactly like it did for ASB 2.x.  Changes are immediate, so you don't need to click a "save" button.  Use the "+" to expand the child folders and "-" to collapse the children folders.  All folders are included by default which is indicated by an enabled checkbox.  Some people might think the checkbox is to exclude folders but it's actually to include (checked=included, unchecked=excluded).

Uncheck the checkbox to exclude the folder.  The "recursive" checkbox is only enabled when a folder is excluded (unchecked).  There might be a bug with this part that I'm testing.  If a parent is excluded, but not recursively, and a child is excluded, then I think the children folder are all excluded.

**Comment by Taurean75** [comment] 2017-12-29 01:04
@eric-bixby, you should put the instructions on that page before releasing the next version.

**Comment by shangles** [comment] 2018-01-02 02:40
Any idea why after installing the beta it keeps disappearing from my list of installed add-ons?  ETA on a non-beta version that includes the folder exclusions?

**Comment by eric-bixby** [comment] 2018-01-02 17:08
Yes, that is how "Load Temporary Add-on" works; It's loaded until you restart Firefox.  Anyway, probably a couple more days.

**Comment by shangles** [comment] 2018-01-03 16:05
v3.2 is out and it resolves this issue.  I say this can be marked as resolved now.  Great work and have a happy new year!

**Comment by shangles** [comment] 2018-01-05 00:31
@eric-bixby Do I need to do anything to change the status from Pending?

**Comment by eric-bixby** [comment] 2018-01-05 00:38
I do that part, thanks.  I've changed it.

**Comment by shangles** [comment] 2018-01-09 01:21
I'm reopening this because today I noticed my bookmarks in the Bookmarks Toolbar folder were alphabetized, rather than sorted manually.  I immediately looked at my ASB settings and the Bookmarks Toolbar folder was still unchecked.  Not sure what caused it to revert and sort the bookmarks in that folder.

I did recently open up Firefox on two other computers in the house (one Mac, one Linux) that are synced with my Firefox Sync account and verified that they were all configured the same.

I'm on 57.0.4 (64-bit) on Windows, mainly, and running version 3.2 of ASB.

**Comment by eric-bixby** [comment] 2018-01-10 05:31
If the checkbox for the Toolbar folder were checked, then I would think it was your preferences being cleared.  I suspect Firefox-Sync might have something to do with it.  It might take me a while to reproduce this problem.

**Comment by eric-bixby** [comment] 2018-06-21 03:28
Try the 3.3 beta 2 release.  This addresses the issue of settings being lost due to cookies being removed.
https://github.com/eric-bixby/auto-sort-bookmarks-webext/releases/tag/v3.3beta2

**Comment by shangles** [comment] 2018-06-21 16:16
Thank you Eric.  How soon until this makes it to the store for auto-updating?

**Comment by eric-bixby** [comment] 2018-06-23 02:17
Fixed in version 3.3, which is now available.

**Closed by eric-bixby** 2018-06-23 02:17 UTC
Labels: Priority: High, Status: Completed, Type: Enhancement
