### ISSUE TITLE
Preferences do not persist across browser sessions.

### ISSUE THREAD

**Issue by akwala** [eric-bixby/auto-sort-bookmarks-webext#65] opened 2017-12-12 05:52 UTC
The preferences revert to the default values when the browser starts. Clicking the Save button after changing preference settings seems to save them only for the current browser session.

**Comment by GuardianMajor** [comment] 2017-12-13 00:33
I am experiencing the same thing, I just came to open an issue and saw you already had.

**Comment by eric-bixby** [comment] 2017-12-13 06:15
I take it you aren't running anything like CCleaner which can be configured to clear the browser's local storage.  There might be a problem when upgrading ASB from 3.0 to 3.1.  Try removing ASB, then install again.

**Comment by akwala** [comment] 2017-12-14 01:42
I removed ASB, restarted Firefox, then installed Firefox again. This didn't fix the issue.

I use [StoragErazor](https://addons.mozilla.org/en-US/firefox/addon/storagerazor/) which erases cache, local storage and IndexedDB, but it doesn't touch databases created by other addons. Regardless, the issue persists after I disabled this addon.

**Comment by eric-bixby** [comment] 2017-12-18 15:40
This add-on uses local storage. It’s odd that your problem persisted after removing the cleaner. Anyway, I’m looking into storing the settings in an alternate place.

**Comment by akwala** [comment] 2017-12-18 17:19
> This add-on uses local storage. It’s odd that your problem persisted after removing the cleaner.

I tested ASB in a fresh profile with no other extensions and saw that the pref settings changes do persist across browser sessions. This suggests that something other than the cleaning addon/s I'm testing might be erasing the local storage.

However, isn't there a "zone" in local storage for addons that the cleaning extensions can exclude? [StoragErazor](https://addons.mozilla.org/en-US/firefox/addon/storagerazor/) claims not to touch this data. [eCleaner](https://addons.mozilla.org/en-US/firefox/addon/ecleaner-forget-button/r has a toggle for including the "Extension zones." Besides, erasing local storage hasn't kept pref settings of other addons from persisting and there must be addons among them that store prefs in local storage.

**Comment by technicianGF** [comment] 2017-12-30 05:36
I have the exact same problem and the trick "uncheck Offline Website Data" didn't work for me.

**Comment by LGotkin** [comment] 2018-01-07 00:08
I find that ASB creates a cookie and, if this cookie is deleted, you are prompted to reconfigure ASB when you restart Firefox.  I was configuring Firefox to automatic delete cookies in the Options / Privacy & Security / History /  Clear history when Firefox closes options. In the Setting under this option, I had set automatic clear Cookies.  Removing that option cleared the problem.
By the way, the cookies ASB created, as shown in Piriform's CCLeaner Free had an identifier like bed03bce-763f-40d6-bed1-ed8f544cf759.  On other systems I have a similar cookie but different identifier was created. For clearing my cookies, I now set CCLeaner to clear cookies but added the above cookie identifier to it's exception list.

**Comment by eric-bixby** [comment] 2018-01-08 04:43
Yes and no.  The API doesn't call it a cookie, but Firefox is treating it like a cookie so they should call it that.  Regardless, I agree.  There are two APIs: local.storage and localStorage; they look similar but one is cleared along with cookies and one is not.  Therefore, I'm going to change API calls to use storage.sync instead which is not supposed to be cleared with cookies plus gets sync'ed when using Firefox-Sync.

**Comment by eric-bixby** [comment] 2018-01-13 19:46
I'm going to try working on this issue this weekend.  Hopefully, it's a simple API change.  I'll post a beta release before formally releasing.

**Comment by GuardianMajor** [comment] 2018-02-15 16:50
Any update on this? The settings are still not being stored and next time you open the browser they are gone and the configuration page for the extension opens up again and again each time. Additionally, the newly added folder excludes does not properly take effect either.

**Comment by eric-bixby** [comment] 2018-02-15 18:36
I started on a fix, but had to take a break due to personal stuff.  I have a solution but it requires some re-design so it will take a little bit more work.  Looks like I'll have some time to work on it this weekend.  Also, as a workaround, disable clearing your cookies.

**Comment by GuardianMajor** [comment] 2018-02-20 04:23
@eric-bixby Thank you, I can understand that life gets in the way, appreciate the effort to get it done.

>  Also, as a workaround, disable clearing cookies.

We think alike, I have already resorted to protecting the cookies for the extension as a means of working around the issue, but it would be reassuring not to have to worry if for some reason they do get cleared. Thanks and looking forward to the fix.

**Comment by Taurean75** [comment] 2018-02-24 01:38
@eric-bixby: Also, executing ""Sort by Name" on an excluded folder resets the folder configuration.

**Comment by eric-bixby** [comment] 2018-02-25 16:50
**Status Update**: I've figured out how to use API for preference storage which doesn't get cleared with cookies (a while ago).  The problem is the library I use for preferences, called weh, uses the localStorage API.  I can't change how weh stores preferences and asked the weh author to change but haven't gotten a response.  I just need to figure how to get weh to use prefs passed to it by the ASB add-on.

**Comment by eric-bixby** [comment] 2018-06-21 03:29
Try the 3.3beta2 release:
https://github.com/eric-bixby/auto-sort-bookmarks-webext/releases/tag/v3.3beta2

**Comment by GuardianMajor** [comment] 2018-06-21 06:55
Will give it a go and let you know.

**Comment by LGotkin** [comment] 2018-06-21 19:57
Seems to work fine.  I set up the Auto-Sort beta options and saved them.  Then looking in the CCleaner application I no longer see a new cookies type object that was previously created by V 3.2.  Tested by changing settings, saving them, cleaning out cookies using the native Firefox Tools / Options / Privacy & Security and clearing all cookies. Setting I had made in the beta were retained.

**Comment by eric-bixby** [comment] 2018-06-23 02:18
This has been fixed in version 3.3, which is now available for download.

**Closed by eric-bixby** 2018-06-23 02:18 UTC
Labels: Priority: Medium, Status: Completed, Type: Bug
