### ISSUE TITLE
Options Window Always opens on Firefox Start

### ISSUE THREAD

**Issue by 13regent** [eric-bixby/auto-sort-bookmarks-webext#71] opened 2018-01-15 20:47 UTC
I installed Auto-Sort Bookmarks today and have been testing it. I have found that when I close Firefox and open it, the Auto-Sort Bookmarks options window opens along with my home page every single time. Tried clearing all history with no luck. The only way to get it to stop doing this was to disable the addon. Any ideas?

**Comment by molitar** [comment] 2018-01-16 14:02
Same problem for me

**Comment by shangles** [comment] 2018-01-16 18:49
It might help the developer(s) if you include specifics about your environment and version of Firefox when reporting bugs.

**Comment by akwala** [comment] 2018-01-16 19:45
+1

**Comment by 13regent** [comment] 2018-01-16 19:54
My system information: Windows 10 version 1709 on Firefox 57.0.4.

**Comment by Arman-2** [comment] 2018-01-19 13:39
Same problems for me: Option window opens and auto sort does not work anymore.
System info: Firefox 57.0.4 (64 bit) on Windows 10. 
Auto Sort Bookmarks 3.2 version 2018-01-03. The add-on worked very well before it was updated.
Success solving the problem! Regards Arman

**Comment by MeiGuddet** [comment] 2018-01-22 22:19
Confirmed. ASB 3.2
System: FF 57.04.0 (64bit)/Windows 10 Prof. 1709

**Comment by hugotheboss65** [comment] 2018-01-27 20:28
The same on my system.
FF 57.04, Windows 10 x64 1709

**Comment by Go5egK** [comment] 2018-01-31 13:22
Me too
W10 1709; Firefox 58.0.1 (64 bit); Ghostery; uBlock Origin; HTTPS Everywhere; Google Analytics opt-out; Unchecky; Bitdefender Internet Security 2018; Malwarebytes 3.3 1; HMA VPN

**Comment by Davspie** [comment] 2018-02-04 18:49
Hi, same as the others
FF 56.0 (32-Bit), Windows 8.1 64Bit.
(I will up date to Quantum 64Bit soon. I was waiting for update for this add-on, etc).
Note: ABS is the only add-on that I have enabled!
(As a developer - I only enable the other couple of installed add-ons when I use them).

The previous ASB version was working brilliantly!
I have just done the 'check for updates' and the newer ASB 3.2 was installed.

This new version does not seem to manage to 'record' the options selected, therefore each time the browser is started the ABS options page is re-deployed.

ABS Options Page - Cancel/Default/Save all result in a lack of 'recorded' state change.
Thus when the browser is again started, the (still un-initialised) options page is displayed by 'default'.

Hope this helps, :-)

**Comment by Davspie** [comment] 2018-03-15 19:09
Hi,
FF 59.0 (64-Bit), Windows 8.1 64Bit.
The issue still exist with the ASB option page re-deploying each time the browser is started up, as per my Feb 4th comment.
This is still the case for ABS version 3.2, (which meant that I had to disable it, while hoping for an update to address the bug).

However I have discovered that by installing the previous versions suitable for Firefox Quantum, (FF 57.0 and greater), that they do not have this 'bug' issue.

Therefore ABS versions 3.0 and 3.1 work, (as they were intended), without the constant re-deploying of the options page on browser start up.

I got these previous ABS 3.0 and ABS 3.1 via this webpage.
https://addons.mozilla.org/en-us/firefox/addon/auto-sort-bookmarks/versions/

I have therfore reverted to ABS 3.1 which I can now at least have enabled and make use of, (until a fix for the ABS 3.2 version 'bug', is forthcoming).
This is good because the ABS plugin is very useful and I kind of missed having it enabled.

Hope this helps, :-)

**Comment by Go5egK** [comment] 2018-03-15 22:48
Hi

Please see the attached email I sent to Eric a couple of days ago.

All the best

Chris (alias Reid)

**Comment by Davspie** [comment] 2018-03-16 01:27
Hi Chris, (Go5egK),

If you are referring me to an email/message 'attachment', then I am not 
managing to locate that or misunderstanding something.

I would also add the following to my earlier comment of 
https://github.com/eric-bixby/auto-sort-bookmarks-webext/issues/71#issuecomment-373490062

Although the ABS versions 3.0 and 3.1 do not suffer from the Options 
Page re-opening on every start up of Firefox, the actual options 
selected do not persist across browser sessions.
That is, the options revert to their defaults the next time that Firefox 
is started, so my contribution suggestion is not as good as I thought.

I generally prefer to have the 'Auto-sort' option disabled and hence 
invoke the bookmark sorting manually.

When next starting Firefox, the 'Auto-sort' option resorts to the 
default of 'enabled', which has the knock on effect of playing havoc 
with the various forms of bookmark synchronisation via cloud based 
mechanisms.

Best wishes,
     David, :-)

**Comment by eric-bixby** [comment] 2018-03-16 05:29
It's a feature in 3.2.  The add-on keeps track of the first-time you've run the add-on as a cookie.  If it's the first-time, then the preferences pop-up.  However, if you are clearing cookies, then the add-on thinks it's always the first-time.  This feature will be removed in the next release.  Also, I'm working on an update to store things in a different place so it doesn't get wiped out.

By the way, I started a FAQ for this: https://github.com/eric-bixby/auto-sort-bookmarks-webext/wiki/Frequently-Asked-Questions-(FAQ)

**Comment by Go5egK** [comment] 2018-03-16 06:44
Thanks Eric for info and link

Chris

**Comment by Davspie** [comment] 2018-03-16 09:58
Hi Eric, (and Chris),

*Thanks for the heads up, and bang on!*

For a very long time I have always set Firefox to clear my history and 
cookies on exit, (apart from the cookies for the explicit domains that I 
added in to the Exceptions... list).
I have reverted Firefox to 'Remember History and hence cookies' in order 
to test ASB 3.2, and it is indeed working as it should be!

As a fellow software developer, I should have twigged, (and it is a 
subtle scenario that I would also have probably fallen into if I was 
doing the development).
*The ASB - cookie being wiped out explains all the 'issues' that I have 
witnessed, such as the options page opening on Firefox start up and the 
selected options not persisting across browser sessions.*

I have used the Firefox - ASB extension for years, and it has very often 
been the only extension that I have consistently enabled, (as a 
developer with screeds of bookmarks to associated stuff).
Hence my 'pressing' interest in continuing to use it.

If the ASB cookie was identifiable in the normal manner such as wrt a 
domain name, then I could easily have added another entry in the 
'Exceptions... list', so as not to delete that on exit.
*None the less, I can toggle between using the stricter 'History' 
settings and enabling/disabling the ASB extension as appropriate, 
depending upon what I am doing.*
This means that I can make proper use of the ASB extension again, which 
I always invoked to sort manually anyway.

Thanks Eric for the reply, (as well as the ASB extension), and thanks 
Chris for steering me in the right direction.
*I did not realise that there was an associated FAQ, otherwise I would 
have checked there first before adding more comments.*

I will look forward to an update for the ASB extension when you get the 
time, however this 'quirk' is no longer a 'pressing priority interest', 
since I now have a workaround that I can employ in the mean time.
I am off to check the ASB - FAQ, ...

Many thanks and best wishes,
     David, :-)

**Comment by eric-bixby** [comment] 2018-05-23 06:31
I finally have a beta version to try:
https://github.com/eric-bixby/auto-sort-bookmarks-webext/releases/tag/v3.3beta1

It still needs more work, but this addresses the problem of prefs being lost when cookies are removed (it's kept in a new place).

What's left to do is also save the excluded folders preference.

**Comment by akwala** [comment] 2018-05-23 21:20
I tested the beta in Firefox Dev Edition. The preferences persisted across browser sessions even after clearing all history data. Anything else you'd like tested?

**Comment by eric-bixby** [comment] 2018-05-25 22:53
That's great.  I'll continue getting the excluded-folder preferences saved, then post another beta to try.

**Comment by eric-bixby** [comment] 2018-06-19 23:41
I finally have a new beta ready for testing that prevents configure-folders settings from getting lost when cookies are removed.

https://github.com/eric-bixby/auto-sort-bookmarks-webext/releases/tag/v3.3beta2

**Comment by eric-bixby** [comment] 2018-06-23 02:16
Fixed in version 3.3

**Closed by eric-bixby** 2018-06-23 02:16 UTC
Labels: Priority: High, Status: Completed, Type: Bug
