### ISSUE TITLE
Bookmark Separators Not Working

### ISSUE THREAD

**Issue by Panjandra** [eric-bixby/auto-sort-bookmarks-webext#66] opened 2017-12-29 14:31 UTC
When I use a Bookmark Separator on the Bookmarks Toolbar, it does not stay in place but is moved to the bottom of the list when sorted by Auto-Sort Bookmarks and is just left in alphabetical order.  The attached file 'auto-sort bookmarks separator corruption' shows a Screenshot of my Bookmarks Toolbar.  I had a Separator between '5' and '08' because, in the Group of '1' to '5', I had 'R4' and 'R4M'.  As you will see from the Screenshot, the whole Bar is just in alphabetical order, with the Separator showing at the end after 'Wim'.

Also, in the Screenshot 'auto-sort bookmarks separator corruption system folders', Auto-Sort Bookmarks pushed 'Most Visited', 'Recent Tags' and 'Recently Bookmarked', together with the Separator, to the bottom of the list rather than being kept together as a Group and separate at the top.

![auto-sort bookmarks separator corruption system folders](https://user-images.githubusercontent.com/34940702/34439085-67cbe356-eca3-11e7-8b8c-0ca8e496b46c.jpg)

![auto-sort bookmarks separator corruption](https://user-images.githubusercontent.com/34940702/34438819-4ca810ce-eca1-11e7-868f-aa3e7e0be205.jpg)

**Comment by Panjandra** [comment] 2017-12-29 14:38
Auto-Sort Bookmarks worked fine until Mozilla Firefox 52.5.

**Comment by Panjandra** [comment] 2018-01-03 17:16
I've also found that it is corrupting the sub-folders in that it is not grouping them at the top of a folder but just putting them, incorrectly, in alphabetic order.  It is as though they were individual bookmards, rather than a folder, where they should be at the top.  I've attached a screenshot to illustrate the point as "Autosort Bookmarks Sub-folder Corruption.jpg"-


![autosort bookmarks sub-folder corruption](https://user-images.githubusercontent.com/34940702/34531290-b75635d4-f0a9-11e7-8a6c-6b8f6b6ec87f.jpg)

**Comment by eric-bixby** [comment] 2018-01-05 04:49
This issue is a duplicate of #56

**Closed by eric-bixby** 2018-01-05 04:49 UTC
