### ISSUE TITLE
Folder Configuration: Excluding folder bookmark toolbar does not work

### ISSUE THREAD

**Issue by Metal-Frog** [eric-bixby/auto-sort-bookmarks-webext#83] opened 2018-07-03 11:20 UTC
I' tried to exclude the bookmark toolbar in FireFox from automatic sorting. But the extension ignores this. And furthermore the settings isn't saved at all ...

**Comment by eric-bixby** [comment] 2018-07-08 18:14
What version of Firefox are you using?

**Comment by Metal-Frog** [comment] 2018-08-28 16:00
Always the latest :)
Currently DevEdition 62.0b20 (64-Bit)

**Comment by JcChimjj** [comment] 2018-11-26 19:59
＃83

**Comment by eric-bixby** [comment] 2022-10-30 00:42
Duplicate of #75

**Closed by eric-bixby** 2022-10-30 00:42 UTC
Labels: Type: Bug, Status: Pending, Priority3: Medium
