### ISSUE TITLE
Configure Folders: can not be saved

### ISSUE THREAD

**Issue by jjaone** [eric-bixby/auto-sort-bookmarks-webext#110] opened 2022-08-09 16:48 UTC
Opening extensions Preferences there is in the bottom of window link to "Configure Folders" which opens a new tab to setup "Folders to Sort" which works as it should.

Problem is that there is no way to save the settings, only a button (x) in the top right corner which just closes the window/tap but the folder sort setup is not saved.

I'm on Linux/Ubuntu 20.04, Firefox 103.0 (64 bit) build:103.0+build1-0ubuntu0.20.04.

![Screenshot from 2022-08-09 19-46-56](https://user-images.githubusercontent.com/5411149/183710240-b65c5a1f-31e4-4c0a-9e3c-2396ce04138f.png)

**Comment by eric-bixby** [comment] 2022-08-09 18:27
First, there is no save button.  Your changes take effect immediately and are saved automatically (you don't need to do anything).
Second, when you say your config is not being saved, what do you mean?  Are you assuming it's not because there is no save button?
You should be able to close the browser and open it again and see your settings.  Also, you can verify it works by manually moving a bookmark out of order, clicking on the "Sort" button, then confirming that it was not moved.

**Comment by jjaone** [comment] 2022-08-10 02:15
1. In GUI if user action open a form in new window/tab it should be able for user to close that view by cance or ok (save) options. That's expeted behaviour by users of most of any application. Sp this is bad design of UI in Settings.
2. The config is not fully saved ( see the two screenshots): 
First I unchecked two folders and their subfolders with the recursive box checked from being sorted automatically.
Then closed that tab and also restarted browser, opened the auto-osrt:settings:configure folders view again, and those tow unchecked folders and thier recursive box are back to initial setup.
So, I was not assuming that the setup is not saved (e.g. because of the flawed UI design) but instead tested it i.e. maked the change and checked whether it was saved or not.
3. Also, checked the sorting of bookmarks which confirmed that those two folser are still auto-sorted, so the setup was not saved but it reverted to the original setup (which auto-sorts all folders).

First screenshot shows the made changes to config:
![Screenshot from 2022-08-10 04-45-49](https://user-images.githubusercontent.com/5411149/183795306-4527af5a-dc16-4266-b91a-56901309f0c0.png)

Second screenshot (after clsoing the tab and restarted browser) shows that the config is back to original
![Screenshot from 2022-08-10 04-56-35](https://user-images.githubusercontent.com/5411149/183795320-e8b1d15c-298e-4ccb-920e-9bf34b996292.png)

**Comment by eric-bixby** [comment] 2022-08-19 14:04
There's no save button for technical reasons, not by design.  Maybe if/when the "configure-folders" feature is overhauled, this can be addressed.

Anyway, it looks like Firefox/Mozilla has changed things (again).  If you enter "about:config" in the address-bar, then search for "bouanto" (the original author).

If you see something like the following, then your preferences have been migrated by Firefox:
extensions.webextensions.ExtensionStorageIDB.migrated.sortbookmarks@bouanto

Looks like Mozilla has changed the way preferences are stored, so that might be the issue.  I need to do some reading/experiments to find out.

In the meantime, this support article from Mozilla might help:
https://support.mozilla.org/en-US/kb/how-to-fix-preferences-wont-save

**Comment by jjaone** [comment] 2022-08-21 09:45
What "technical" reasons? You didn't specify any!

BTW: checking the other open issues in this repo it appears that half of user reports are about this same bug "configure folders setting is not stored and/or reverts to original setting. "

Anyway, instead of blaming this bug on Mozilla or on users making these reports or on any other than yourself why don't you just fix your misbehaving plugin, or ask help from the community if you don't know how!

**Comment by eric-bixby** [comment] 2022-08-21 13:21
If you read my response, I did not blame anyone.  Sometimes the issue is Firefox or the user, but I did not say it definitely was.

I said I would look into it, but dealing with your arrogance makes this a complete waste of my time.

**Comment by eric-bixby** [comment] 2022-08-21 16:08
Duplicate of #83

**Closed by eric-bixby** 2022-08-21 16:08 UTC
