### ISSUE TITLE
Settings Window Opens On FF Startup

### ISSUE THREAD

**Issue by dave47** [eric-bixby/auto-sort-bookmarks-webext#67] opened 2018-01-04 13:19 UTC
windows 7  FF 54.01 Auto sort 3.2

**Comment by Selemia** [comment] 2018-01-04 15:43
Thank you for this add-on Eric !
Same problem as dave47 here.
I add that settings are no more saved if I close and restart Firefox.

**Comment by eric-bixby** [comment] 2018-01-05 04:57
This is a duplicate of #65 

Starting with ASB 3.2, the "first time" it's run, the add-on shows the settings page.  ASB detects "first time" by looking for the presence of "version" in local.storage; if the value is less than the current version or missing, then the add-on thinks it's the "first time".  The problem is that the local.storage (same place preferences are stored) values are being cleared.

**Closed by eric-bixby** 2018-01-05 04:57 UTC
